POST http://localhost:5000/users
Content-Type: application/json

{
    "name": "Raihan Hossain",
    "email": "rjibon49@gmail.com",
    "phoneNumber": "12345678",
    "password": "123456",
    "confirmPassword": "123456",
    "role": "admin"
}


###
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "rjibon49@gmail.com",
    "password": "123446",
}

###
GET http://localhost:5000/users

{
    "email": "rjibon49@gmail.com",
    "password": "123457"
}


###
DELETE  http://localhost:5000/logout

{
    "email": "rjibon49@gmail.com",
    "password": "123457"
}